
name: Build OpenRV Windows (VFX-CY2024)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 480

    env:
      QT_VERSION: 5.15.2
      PYTHON_VERSION: "3.11"

    steps:

    - name: Enable Windows long paths
      run: git config --system core.longpaths true

    - name: Checkout OpenRV
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install build tools
      shell: powershell
      run: |
        choco install strawberryperl nasm winflexbison pkgconfiglite cmake -y

        python -m pip install --upgrade pip
        pip install pyyaml requests wheel numpy

        # add choco bin to PATH
        echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH

    - name: Fix flex command for CMake
      shell: powershell
      run: |
        copy C:\ProgramData\chocolatey\bin\win_flex.exe C:\ProgramData\chocolatey\bin\flex.exe
        copy C:\ProgramData\chocolatey\bin\win_bison.exe C:\ProgramData\chocolatey\bin\bison.exe

    - name: Install Qt 5.15 + WebEngine
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ env.QT_VERSION }}
        arch: win64_msvc2019_64
        modules: qtwebengine
        dir: C:\Qt

    - name: Setup MSYS2 tools
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          autoconf automake bison flex git libtool nasm p7zip patch unzip zip
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-libarchive
          mingw-w64-x86_64-glew

    - name: Configure OpenRV
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |

        export PATH="$PATH:/c/Program Files/CMake/bin:/c/msys64/mingw64/bin:/c/ProgramData/chocolatey/bin"
        export QT_HOME="/c/Qt/5.15.2/msvc2019_64"

        cd "$(cygpath -u "$GITHUB_WORKSPACE")"

        cmake -B build \
          -G "Visual Studio 17 2022" \
          -A x64 \
          -DCMAKE_PREFIX_PATH=$QT_HOME \
          -DRV_DEPS_QT_LOCATION=$QT_HOME \
          -DRV_DEPS_WIN_PERL_ROOT=/c/Strawberry/perl/bin

    - name: Build OpenRV
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cd "$(cygpath -u "$GITHUB_WORKSPACE")"
        cmake --build build --config Release --parallel 4

    - name: Install OpenRV
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cd "$(cygpath -u "$GITHUB_WORKSPACE")"
        cmake --install build --prefix install

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenRV-Windows
        path: install
